// ***DO NOT EDIT THIS FILE - IT IS AUTOMATICALLY GENERATED BY CMAKE***

#include <osgEarthExtensions/normalmap/NormalMapShaders>

using namespace osgEarth::NormalMap;

Shaders::Shaders()
{
    Vertex = "NormalMap.vert.glsl";
    _sources[Vertex] = OE_MULTILINE($__HASHTAG__version 110\n
$__HASHTAG__pragma vp_entryPoint "oe_nmap_vertex"\n
$__HASHTAG__pragma vp_location   "vertex_model"\n
$__HASHTAG__pragma vp_order      "0.5"\n
\n
varying vec3 oe_Normal;\n
varying vec4 oe_layer_tilec;\n
\n
uniform mat4 oe_nmap_normalTexMatrix;\n
varying vec4 oe_nmap_normalCoords;\n
varying mat3 oe_nmap_TBN;\n
\n
void oe_nmap_vertex(inout vec4 VertexMODEL)\n
{\n
    // calculate the sampling coordinates for the normal texture\n
    oe_nmap_normalCoords = oe_nmap_normalTexMatrix * oe_layer_tilec;\n
\n
    // form the matrix that will transform a normal vector from\n
    // tangent space to model space in the fragment shader.\n
    // We expect the vertex normal to be a simple UP vector.\n
    vec3 B = vec3(0,1,0);\n
    vec3 N = oe_Normal;\n
    vec3 T = normalize(cross(B,N));\n
    oe_nmap_TBN = gl_NormalMatrix * mat3(T, B, N);\n
}\n
);

    Fragment = "NormalMap.frag.glsl";
    _sources[Fragment] = OE_MULTILINE($__HASHTAG__version 110\n
$__HASHTAG__pragma vp_entryPoint "oe_nmap_fragment"\n
$__HASHTAG__pragma vp_location   "fragment_coloring"\n
$__HASHTAG__pragma vp_order      "0.2"\n
\n
// stage global:\n
vec3 oe_global_Normal;\n
\n
uniform vec4 oe_tile_key;\n
uniform sampler2D oe_nmap_normalTex;\n
varying vec4 oe_nmap_normalCoords;\n
varying mat3 oe_nmap_TBN;\n
\n
void oe_nmap_fragment(inout vec4 color)\n
{\n
    vec4 encodedNormal = texture2D(oe_nmap_normalTex, oe_nmap_normalCoords.st);\n
    vec3 normalTangent = normalize(encodedNormal.xyz*2.0-1.0);\n
    oe_global_Normal = normalize(oe_nmap_TBN * normalTangent);\n
\n
    // visualize curvature:\n
    //color.rgb = vec3(0,0,0);\n
    //if(decoded.a >= 0.4) color.r = 1.0;\n
    //if(decoded.a <= -0.4) color.b = 1.0;\n
\n
    // visualize normals:\n
    //color.rgb = encodedNormal.xyz;\n
}\n
\n
);
}
